services:
  postgres:
    image: postgres:16
    container_name: image-processing-engine-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
      POSTGRES_DB: presets
      PORT: 5432
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d:ro

volumes:
  postgres-data:
