name: Compile and run 

on:
  push:
  pull_request:

jobs:
  build_native:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: make
  build_wasm:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: mymindstorm/setup-emsdk@v14
      - run: emcc -v
      - run: make wasm
  run-test:
    name: "Identity tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Tests
        run: |
          mkdir -p tests/test_output
          make test